config/routes.rb
Rails.application.routes.draw do
  resources :valors
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/valor.rb
class Valor < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/valors_controller.rb
class ValorsController < ApplicationController
  before_action :set_valor, only: [:show, :edit, :update, :destroy]

  # GET /valors
  # GET /valors.json
  def index
    @valors = Valor.all
  end

  # GET /valors/1
  # GET /valors/1.json
  def show
  end

  # GET /valors/new
  def new
    @valor = Valor.new
  end

  # GET /valors/1/edit
  def edit
  end

  # POST /valors
  # POST /valors.json
  def create
    @valor = Valor.new(valor_params)

    respond_to do |format|
      if @valor.save
        format.html { redirect_to @valor, notice: 'Valor was successfully created.' }
        format.json { render :show, status: :created, location: @valor }
      else
        format.html { render :new }
        format.json { render json: @valor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /valors/1
  # PATCH/PUT /valors/1.json
  def update
    respond_to do |format|
      if @valor.update(valor_params)
        format.html { redirect_to @valor, notice: 'Valor was successfully updated.' }
        format.json { render :show, status: :ok, location: @valor }
      else
        format.html { render :edit }
        format.json { render json: @valor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /valors/1
  # DELETE /valors/1.json
  def destroy
    @valor.destroy
    respond_to do |format|
      format.html { redirect_to valors_url, notice: 'Valor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_valor
      @valor = Valor.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def valor_params
      params.require(:valor).permit(:valor1)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/valors_helper.rb
module ValorsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Midepa</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/valors/_form.html.erb
<%= form_with(model: valor, local: true) do |form| %>
  <% if valor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(valor.errors.count, "error") %> prohibited this valor from being saved:</h2>

      <ul>
      <% valor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :valor1 %>
    <%= form.text_field :valor1 %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/valors/edit.html.erb
<h1>Editing Valor</h1>

<%= render 'form', valor: @valor %>

<%= link_to 'Show', @valor %> |
<%= link_to 'Back', valors_path %>

app/views/valors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Valors</h1>

<table>
  <thead>
    <tr>
      <th>Valor1</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @valors.each do |valor| %>
      <tr>
        <td><%= valor.valor1 %></td>
        <td><%= link_to 'Show', valor %></td>
        <td><%= link_to 'Edit', edit_valor_path(valor) %></td>
        <td><%= link_to 'Destroy', valor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Valor', new_valor_path %>

app/views/valors/new.html.erb
<h1>New Valor</h1>

<%= render 'form', valor: @valor %>

<%= link_to 'Back', valors_path %>

app/views/valors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Valor1:</strong>
  <%= @valor.valor1 %>
</p>

<%= link_to 'Edit', edit_valor_path(@valor) %> |
<%= link_to 'Back', valors_path %>